//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 5/15/2016 8:42:38 PM
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// There are no comments for ApplicationData in the schema.
    /// </summary>
    public partial class ApplicationData : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ApplicationData object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApplicationData(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "LightSwitchApplication", "LightSwitchApplication.Implementation");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Appointments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Appointment> Appointments
        {
            get
            {
                if ((this._Appointments == null))
                {
                    this._Appointments = base.CreateQuery<Appointment>("Appointments");
                }
                return this._Appointments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Appointment> _Appointments;
        /// <summary>
        /// There are no comments for InvoiceDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<InvoiceDetail> InvoiceDetails
        {
            get
            {
                if ((this._InvoiceDetails == null))
                {
                    this._InvoiceDetails = base.CreateQuery<InvoiceDetail>("InvoiceDetails");
                }
                return this._InvoiceDetails;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<InvoiceDetail> _InvoiceDetails;
        /// <summary>
        /// There are no comments for Invoices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Invoice> Invoices
        {
            get
            {
                if ((this._Invoices == null))
                {
                    this._Invoices = base.CreateQuery<Invoice>("Invoices");
                }
                return this._Invoices;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Invoice> _Invoices;
        /// <summary>
        /// There are no comments for Patients in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Patient> Patients
        {
            get
            {
                if ((this._Patients == null))
                {
                    this._Patients = base.CreateQuery<Patient>("Patients");
                }
                return this._Patients;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Patient> _Patients;
        /// <summary>
        /// There are no comments for Appointments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAppointments(Appointment appointment)
        {
            base.AddObject("Appointments", appointment);
        }
        /// <summary>
        /// There are no comments for InvoiceDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToInvoiceDetails(InvoiceDetail invoiceDetail)
        {
            base.AddObject("InvoiceDetails", invoiceDetail);
        }
        /// <summary>
        /// There are no comments for Invoices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToInvoices(Invoice invoice)
        {
            base.AddObject("Invoices", invoice);
        }
        /// <summary>
        /// There are no comments for Patients in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPatients(Patient patient)
        {
            base.AddObject("Patients", patient);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataserv" +
                "ices/metadata\" m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\"><Schema " +
                "xmlns:annotation=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" Names" +
                "pace=\"LightSwitchApplication\" Alias=\"Self\" xmlns=\"http://schemas.microsoft.com/a" +
                "do/2008/09/edm\"><EntityType Name=\"Appointment\"><Key><PropertyRef Name=\"Id\" /></K" +
                "ey><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGenerat" +
                "edPattern=\"Identity\" /><Property Name=\"AppointmentTime\" Type=\"Edm.DateTime\" Null" +
                "able=\"false\" /><Property Name=\"AppointmentDate\" Type=\"Edm.DateTime\" Nullable=\"fa" +
                "lse\" /><Property Name=\"AppointmentType\" Type=\"Edm.Int16\" Nullable=\"false\" /><Pro" +
                "perty Name=\"DoctorNotes\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"App" +
                "ointment_Patient\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"CreatedBy\"" +
                " Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Created\" Type=\"Edm.DateTime" +
                "Offset\" /><Property Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Prope" +
                "rty Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowVersion\" Type" +
                "=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGenerated" +
                "Pattern=\"Computed\" /><NavigationProperty Name=\"Patient\" Relationship=\"LightSwitc" +
                "hApplication.Appointment_Patient\" ToRole=\"Patient\" FromRole=\"Appointment\" /></En" +
                "tityType><EntityType Name=\"InvoiceDetail\"><Key><PropertyRef Name=\"Id\" /></Key><P" +
                "roperty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPat" +
                "tern=\"Identity\" /><Property Name=\"Quantity\" Type=\"Edm.Int32\" Nullable=\"false\" />" +
                "<Property Name=\"UnitPrice\" Type=\"Edm.Decimal\" Nullable=\"false\" Precision=\"18\" Sc" +
                "ale=\"2\" /><Property Name=\"Invoice_InvoiceDetail\" Type=\"Edm.Int32\" Nullable=\"fals" +
                "e\" /><Property Name=\"Product_ProductID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Pro" +
                "perty Name=\"CreatedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Creat" +
                "ed\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"ModifiedBy\" Type=\"Edm.String\" Ma" +
                "xLength=\"255\" /><Property Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><Property " +
                "Name=\"RowVersion\" Type=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" ann" +
                "otation:StoreGeneratedPattern=\"Computed\" /><NavigationProperty Name=\"Invoice\" Re" +
                "lationship=\"LightSwitchApplication.Invoice_InvoiceDetail\" ToRole=\"Invoice\" FromR" +
                "ole=\"InvoiceDetail\" /></EntityType><EntityType Name=\"Invoice\"><Key><PropertyRef " +
                "Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotati" +
                "on:StoreGeneratedPattern=\"Identity\" /><Property Name=\"InvoiceDate\" Type=\"Edm.Dat" +
                "eTime\" Nullable=\"false\" /><Property Name=\"InvoiceDue\" Type=\"Edm.DateTime\" Nullab" +
                "le=\"false\" /><Property Name=\"InvoiceStatus\" Type=\"Edm.Int32\" Nullable=\"false\" />" +
                "<Property Name=\"ShipDate\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=" +
                "\"Invoice_Patient\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"CreatedBy\"" +
                " Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Created\" Type=\"Edm.DateTime" +
                "Offset\" /><Property Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Prope" +
                "rty Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowVersion\" Type" +
                "=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGenerated" +
                "Pattern=\"Computed\" /><NavigationProperty Name=\"Patient\" Relationship=\"LightSwitc" +
                "hApplication.Invoice_Patient\" ToRole=\"Patient\" FromRole=\"Invoice\" /><NavigationP" +
                "roperty Name=\"InvoiceDetails\" Relationship=\"LightSwitchApplication.Invoice_Invoi" +
                "ceDetail\" ToRole=\"InvoiceDetail\" FromRole=\"Invoice\" /></EntityType><EntityType N" +
                "ame=\"Patient\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm." +
                "Int32\" Nullable=\"false\" annotation:StoreGeneratedPattern=\"Identity\" /><Property " +
                "Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property Name=" +
                "\"Street\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property Name=\"St" +
                "reet2\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"City\" Type=\"Edm.Strin" +
                "g\" Nullable=\"false\" MaxLength=\"255\" /><Property Name=\"State\" Type=\"Edm.String\" N" +
                "ullable=\"false\" MaxLength=\"255\" /><Property Name=\"Zip\" Type=\"Edm.String\" Nullabl" +
                "e=\"false\" MaxLength=\"255\" /><Property Name=\"PrimaryPhone\" Type=\"Edm.String\" MaxL" +
                "ength=\"255\" /><Property Name=\"SecondaryPhone\" Type=\"Edm.String\" MaxLength=\"255\" " +
                "/><Property Name=\"Email\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Pol" +
                "icyNumber\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"12\" /><Property Name=\"R" +
                "owVersion\" Type=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" annotation" +
                ":StoreGeneratedPattern=\"Computed\" /><NavigationProperty Name=\"Invoices\" Relation" +
                "ship=\"LightSwitchApplication.Invoice_Patient\" ToRole=\"Invoice\" FromRole=\"Patient" +
                "\" /><NavigationProperty Name=\"Appointments\" Relationship=\"LightSwitchApplication" +
                ".Appointment_Patient\" ToRole=\"Appointment\" FromRole=\"Patient\" /></EntityType><As" +
                "sociation Name=\"Invoice_InvoiceDetail\"><End Role=\"Invoice\" Type=\"LightSwitchAppl" +
                "ication.Invoice\" Multiplicity=\"1\" /><End Role=\"InvoiceDetail\" Type=\"LightSwitchA" +
                "pplication.InvoiceDetail\" Multiplicity=\"*\" /><ReferentialConstraint><Principal R" +
                "ole=\"Invoice\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"InvoiceDetai" +
                "l\"><PropertyRef Name=\"Invoice_InvoiceDetail\" /></Dependent></ReferentialConstrai" +
                "nt></Association><Association Name=\"Invoice_Patient\"><End Role=\"Patient\" Type=\"L" +
                "ightSwitchApplication.Patient\" Multiplicity=\"1\" /><End Role=\"Invoice\" Type=\"Ligh" +
                "tSwitchApplication.Invoice\" Multiplicity=\"*\" /><ReferentialConstraint><Principal" +
                " Role=\"Patient\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"Invoice\"><" +
                "PropertyRef Name=\"Invoice_Patient\" /></Dependent></ReferentialConstraint></Assoc" +
                "iation><Association Name=\"Appointment_Patient\"><End Role=\"Patient\" Type=\"LightSw" +
                "itchApplication.Patient\" Multiplicity=\"1\" /><End Role=\"Appointment\" Type=\"LightS" +
                "witchApplication.Appointment\" Multiplicity=\"*\" /><ReferentialConstraint><Princip" +
                "al Role=\"Patient\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"Appointm" +
                "ent\"><PropertyRef Name=\"Appointment_Patient\" /></Dependent></ReferentialConstrai" +
                "nt></Association><EntityContainer Name=\"ApplicationData\" m:IsDefaultEntityContai" +
                "ner=\"true\"><EntitySet Name=\"Appointments\" EntityType=\"LightSwitchApplication.App" +
                "ointment\" /><EntitySet Name=\"InvoiceDetails\" EntityType=\"LightSwitchApplication." +
                "InvoiceDetail\" /><EntitySet Name=\"Invoices\" EntityType=\"LightSwitchApplication.I" +
                "nvoice\" /><EntitySet Name=\"Patients\" EntityType=\"LightSwitchApplication.Patient\"" +
                " /><AssociationSet Name=\"Invoice_InvoiceDetail\" Association=\"LightSwitchApplicat" +
                "ion.Invoice_InvoiceDetail\"><End Role=\"Invoice\" EntitySet=\"Invoices\" /><End Role=" +
                "\"InvoiceDetail\" EntitySet=\"InvoiceDetails\" /></AssociationSet><AssociationSet Na" +
                "me=\"Invoice_Patient\" Association=\"LightSwitchApplication.Invoice_Patient\"><End R" +
                "ole=\"Patient\" EntitySet=\"Patients\" /><End Role=\"Invoice\" EntitySet=\"Invoices\" />" +
                "</AssociationSet><AssociationSet Name=\"Appointment_Patient\" Association=\"LightSw" +
                "itchApplication.Appointment_Patient\"><End Role=\"Patient\" EntitySet=\"Patients\" />" +
                "<End Role=\"Appointment\" EntitySet=\"Appointments\" /></AssociationSet><FunctionImp" +
                "ort Name=\"UpcomingAppointments\" ReturnType=\"Collection(LightSwitchApplication.Ap" +
                "pointment)\" EntitySet=\"Appointments\" m:HttpMethod=\"GET\" /><FunctionImport Name=\"" +
                "Microsoft_LightSwitch_GetCanInformation\" ReturnType=\"Edm.String\" m:HttpMethod=\"G" +
                "ET\"><Parameter Name=\"dataServiceMembers\" Type=\"Edm.String\" Mode=\"In\" /></Functio" +
                "nImport></EntityContainer></Schema></edmx:DataServices></ed";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "mx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Appointment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Appointments")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Appointment : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Appointment object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="appointmentTime">Initial value of AppointmentTime.</param>
        /// <param name="appointmentDate">Initial value of AppointmentDate.</param>
        /// <param name="appointmentType">Initial value of AppointmentType.</param>
        /// <param name="appointment_Patient">Initial value of Appointment_Patient.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Appointment CreateAppointment(int ID, global::System.DateTime appointmentTime, global::System.DateTime appointmentDate, short appointmentType, int appointment_Patient, byte[] rowVersion)
        {
            Appointment appointment = new Appointment();
            appointment.Id = ID;
            appointment.AppointmentTime = appointmentTime;
            appointment.AppointmentDate = appointmentDate;
            appointment.AppointmentType = appointmentType;
            appointment.Appointment_Patient = appointment_Patient;
            appointment.RowVersion = rowVersion;
            return appointment;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property AppointmentTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime AppointmentTime
        {
            get
            {
                return this._AppointmentTime;
            }
            set
            {
                this.OnAppointmentTimeChanging(value);
                if (object.Equals(this.AppointmentTime, value))
                {
                    return;
                }
                this._AppointmentTime = value;
                this.OnAppointmentTimeChanged();
                this.OnPropertyChanged("AppointmentTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _AppointmentTime;
        partial void OnAppointmentTimeChanging(global::System.DateTime value);
        partial void OnAppointmentTimeChanged();
        /// <summary>
        /// There are no comments for Property AppointmentDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime AppointmentDate
        {
            get
            {
                return this._AppointmentDate;
            }
            set
            {
                this.OnAppointmentDateChanging(value);
                if (object.Equals(this.AppointmentDate, value))
                {
                    return;
                }
                this._AppointmentDate = value;
                this.OnAppointmentDateChanged();
                this.OnPropertyChanged("AppointmentDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _AppointmentDate;
        partial void OnAppointmentDateChanging(global::System.DateTime value);
        partial void OnAppointmentDateChanged();
        /// <summary>
        /// There are no comments for Property AppointmentType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short AppointmentType
        {
            get
            {
                return this._AppointmentType;
            }
            set
            {
                this.OnAppointmentTypeChanging(value);
                if (object.Equals(this.AppointmentType, value))
                {
                    return;
                }
                this._AppointmentType = value;
                this.OnAppointmentTypeChanged();
                this.OnPropertyChanged("AppointmentType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _AppointmentType;
        partial void OnAppointmentTypeChanging(short value);
        partial void OnAppointmentTypeChanged();
        /// <summary>
        /// There are no comments for Property DoctorNotes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DoctorNotes
        {
            get
            {
                return this._DoctorNotes;
            }
            set
            {
                this.OnDoctorNotesChanging(value);
                if (object.Equals(this.DoctorNotes, value))
                {
                    return;
                }
                this._DoctorNotes = value;
                this.OnDoctorNotesChanged();
                this.OnPropertyChanged("DoctorNotes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DoctorNotes;
        partial void OnDoctorNotesChanging(string value);
        partial void OnDoctorNotesChanged();
        /// <summary>
        /// There are no comments for Property Appointment_Patient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Appointment_Patient
        {
            get
            {
                return this._Appointment_Patient;
            }
            set
            {
                this.OnAppointment_PatientChanging(value);
                if (object.Equals(this.Appointment_Patient, value))
                {
                    return;
                }
                this._Appointment_Patient = value;
                this.OnAppointment_PatientChanged();
                this.OnPropertyChanged("Appointment_Patient");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Appointment_Patient;
        partial void OnAppointment_PatientChanging(int value);
        partial void OnAppointment_PatientChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Patient Patient
        {
            get
            {
                this.@__Patient.EnsureValueInitialized();
                return this._Patient;
            }
            set
            {
                Patient previous = this.Patient;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Patient = null;
                    this.@__Patient.OnValueSet();
                    previous.Appointments.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Appointment_Patient = value.Id;
                    }
                    else
                    {
                        this.Appointment_Patient = default(int);
                    }
                }
                this._Patient = value;
                this.@__Patient.OnValueSet();
                if ((value != null))
                {
                    value.@__Appointments.Add(this);
                }
                this.___OnPropertyChanged("Patient");
                this.OnPropertyChanged("Patient");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Patient _Patient;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.InvoiceDetail in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("InvoiceDetails")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class InvoiceDetail : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new InvoiceDetail object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="quantity">Initial value of Quantity.</param>
        /// <param name="unitPrice">Initial value of UnitPrice.</param>
        /// <param name="invoice_InvoiceDetail">Initial value of Invoice_InvoiceDetail.</param>
        /// <param name="product_ProductID">Initial value of Product_ProductID.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static InvoiceDetail CreateInvoiceDetail(int ID, int quantity, decimal unitPrice, int invoice_InvoiceDetail, int product_ProductID, byte[] rowVersion)
        {
            InvoiceDetail invoiceDetail = new InvoiceDetail();
            invoiceDetail.Id = ID;
            invoiceDetail.Quantity = quantity;
            invoiceDetail.UnitPrice = unitPrice;
            invoiceDetail.Invoice_InvoiceDetail = invoice_InvoiceDetail;
            invoiceDetail.Product_ProductID = product_ProductID;
            invoiceDetail.RowVersion = rowVersion;
            return invoiceDetail;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                if (object.Equals(this.Quantity, value))
                {
                    return;
                }
                this._Quantity = value;
                this.OnQuantityChanged();
                this.OnPropertyChanged("Quantity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Quantity;
        partial void OnQuantityChanging(int value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Property UnitPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal UnitPrice
        {
            get
            {
                return this._UnitPrice;
            }
            set
            {
                this.OnUnitPriceChanging(value);
                if (object.Equals(this.UnitPrice, value))
                {
                    return;
                }
                this._UnitPrice = value;
                this.OnUnitPriceChanged();
                this.OnPropertyChanged("UnitPrice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _UnitPrice;
        partial void OnUnitPriceChanging(decimal value);
        partial void OnUnitPriceChanged();
        /// <summary>
        /// There are no comments for Property Invoice_InvoiceDetail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Invoice_InvoiceDetail
        {
            get
            {
                return this._Invoice_InvoiceDetail;
            }
            set
            {
                this.OnInvoice_InvoiceDetailChanging(value);
                if (object.Equals(this.Invoice_InvoiceDetail, value))
                {
                    return;
                }
                this._Invoice_InvoiceDetail = value;
                this.OnInvoice_InvoiceDetailChanged();
                this.OnPropertyChanged("Invoice_InvoiceDetail");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Invoice_InvoiceDetail;
        partial void OnInvoice_InvoiceDetailChanging(int value);
        partial void OnInvoice_InvoiceDetailChanged();
        /// <summary>
        /// There are no comments for Property Product_ProductID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Product_ProductID
        {
            get
            {
                return this._Product_ProductID;
            }
            set
            {
                this.OnProduct_ProductIDChanging(value);
                if (object.Equals(this.Product_ProductID, value))
                {
                    return;
                }
                this._Product_ProductID = value;
                this.OnProduct_ProductIDChanged();
                this.OnPropertyChanged("Product_ProductID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Product_ProductID;
        partial void OnProduct_ProductIDChanging(int value);
        partial void OnProduct_ProductIDChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Invoice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Invoice Invoice
        {
            get
            {
                this.@__Invoice.EnsureValueInitialized();
                return this._Invoice;
            }
            set
            {
                Invoice previous = this.Invoice;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Invoice = null;
                    this.@__Invoice.OnValueSet();
                    previous.InvoiceDetails.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Invoice_InvoiceDetail = value.Id;
                    }
                    else
                    {
                        this.Invoice_InvoiceDetail = default(int);
                    }
                }
                this._Invoice = value;
                this.@__Invoice.OnValueSet();
                if ((value != null))
                {
                    value.@__InvoiceDetails.Add(this);
                }
                this.___OnPropertyChanged("Invoice");
                this.OnPropertyChanged("Invoice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Invoice _Invoice;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Invoice in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Invoices")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Invoice : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Invoice object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="invoiceDate">Initial value of InvoiceDate.</param>
        /// <param name="invoiceDue">Initial value of InvoiceDue.</param>
        /// <param name="invoiceStatus">Initial value of InvoiceStatus.</param>
        /// <param name="shipDate">Initial value of ShipDate.</param>
        /// <param name="invoice_Patient">Initial value of Invoice_Patient.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Invoice CreateInvoice(int ID, global::System.DateTime invoiceDate, global::System.DateTime invoiceDue, int invoiceStatus, global::System.DateTime shipDate, int invoice_Patient, byte[] rowVersion)
        {
            Invoice invoice = new Invoice();
            invoice.Id = ID;
            invoice.InvoiceDate = invoiceDate;
            invoice.InvoiceDue = invoiceDue;
            invoice.InvoiceStatus = invoiceStatus;
            invoice.ShipDate = shipDate;
            invoice.Invoice_Patient = invoice_Patient;
            invoice.RowVersion = rowVersion;
            return invoice;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property InvoiceDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime InvoiceDate
        {
            get
            {
                return this._InvoiceDate;
            }
            set
            {
                this.OnInvoiceDateChanging(value);
                if (object.Equals(this.InvoiceDate, value))
                {
                    return;
                }
                this._InvoiceDate = value;
                this.OnInvoiceDateChanged();
                this.OnPropertyChanged("InvoiceDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _InvoiceDate;
        partial void OnInvoiceDateChanging(global::System.DateTime value);
        partial void OnInvoiceDateChanged();
        /// <summary>
        /// There are no comments for Property InvoiceDue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime InvoiceDue
        {
            get
            {
                return this._InvoiceDue;
            }
            set
            {
                this.OnInvoiceDueChanging(value);
                if (object.Equals(this.InvoiceDue, value))
                {
                    return;
                }
                this._InvoiceDue = value;
                this.OnInvoiceDueChanged();
                this.OnPropertyChanged("InvoiceDue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _InvoiceDue;
        partial void OnInvoiceDueChanging(global::System.DateTime value);
        partial void OnInvoiceDueChanged();
        /// <summary>
        /// There are no comments for Property InvoiceStatus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int InvoiceStatus
        {
            get
            {
                return this._InvoiceStatus;
            }
            set
            {
                this.OnInvoiceStatusChanging(value);
                if (object.Equals(this.InvoiceStatus, value))
                {
                    return;
                }
                this._InvoiceStatus = value;
                this.OnInvoiceStatusChanged();
                this.OnPropertyChanged("InvoiceStatus");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _InvoiceStatus;
        partial void OnInvoiceStatusChanging(int value);
        partial void OnInvoiceStatusChanged();
        /// <summary>
        /// There are no comments for Property ShipDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ShipDate
        {
            get
            {
                return this._ShipDate;
            }
            set
            {
                this.OnShipDateChanging(value);
                if (object.Equals(this.ShipDate, value))
                {
                    return;
                }
                this._ShipDate = value;
                this.OnShipDateChanged();
                this.OnPropertyChanged("ShipDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ShipDate;
        partial void OnShipDateChanging(global::System.DateTime value);
        partial void OnShipDateChanged();
        /// <summary>
        /// There are no comments for Property Invoice_Patient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Invoice_Patient
        {
            get
            {
                return this._Invoice_Patient;
            }
            set
            {
                this.OnInvoice_PatientChanging(value);
                if (object.Equals(this.Invoice_Patient, value))
                {
                    return;
                }
                this._Invoice_Patient = value;
                this.OnInvoice_PatientChanged();
                this.OnPropertyChanged("Invoice_Patient");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Invoice_Patient;
        partial void OnInvoice_PatientChanging(int value);
        partial void OnInvoice_PatientChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Patient Patient
        {
            get
            {
                this.@__Patient.EnsureValueInitialized();
                return this._Patient;
            }
            set
            {
                Patient previous = this.Patient;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Patient = null;
                    this.@__Patient.OnValueSet();
                    previous.Invoices.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Invoice_Patient = value.Id;
                    }
                    else
                    {
                        this.Invoice_Patient = default(int);
                    }
                }
                this._Patient = value;
                this.@__Patient.OnValueSet();
                if ((value != null))
                {
                    value.@__Invoices.Add(this);
                }
                this.___OnPropertyChanged("Patient");
                this.OnPropertyChanged("Patient");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Patient _Patient;
        /// <summary>
        /// There are no comments for InvoiceDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<InvoiceDetail> InvoiceDetails
        {
            get
            {
                this.@__InvoiceDetails.EnsureValueInitialized();
                return this._InvoiceDetails;
            }
            set
            {
                this._InvoiceDetails = value;
                this.OnPropertyChanged("InvoiceDetails");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<InvoiceDetail> _InvoiceDetails = new global::System.Data.Services.Client.DataServiceCollection<InvoiceDetail>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Patient in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Patients")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Patient : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Patient object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="street">Initial value of Street.</param>
        /// <param name="city">Initial value of City.</param>
        /// <param name="state">Initial value of State.</param>
        /// <param name="zip">Initial value of Zip.</param>
        /// <param name="policyNumber">Initial value of PolicyNumber.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Patient CreatePatient(int ID, string name, string street, string city, string state, string zip, string policyNumber, byte[] rowVersion)
        {
            Patient patient = new Patient();
            patient.Id = ID;
            patient.Name = name;
            patient.Street = street;
            patient.City = city;
            patient.State = state;
            patient.Zip = zip;
            patient.PolicyNumber = policyNumber;
            patient.RowVersion = rowVersion;
            return patient;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                if (object.Equals(this.Name, value))
                {
                    return;
                }
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Street in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Street
        {
            get
            {
                return this._Street;
            }
            set
            {
                this.OnStreetChanging(value);
                if (object.Equals(this.Street, value))
                {
                    return;
                }
                this._Street = value;
                this.OnStreetChanged();
                this.OnPropertyChanged("Street");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Street;
        partial void OnStreetChanging(string value);
        partial void OnStreetChanged();
        /// <summary>
        /// There are no comments for Property Street2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Street2
        {
            get
            {
                return this._Street2;
            }
            set
            {
                this.OnStreet2Changing(value);
                if (object.Equals(this.Street2, value))
                {
                    return;
                }
                this._Street2 = value;
                this.OnStreet2Changed();
                this.OnPropertyChanged("Street2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Street2;
        partial void OnStreet2Changing(string value);
        partial void OnStreet2Changed();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                if (object.Equals(this.City, value))
                {
                    return;
                }
                this._City = value;
                this.OnCityChanged();
                this.OnPropertyChanged("City");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property State in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                if (object.Equals(this.State, value))
                {
                    return;
                }
                this._State = value;
                this.OnStateChanged();
                this.OnPropertyChanged("State");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _State;
        partial void OnStateChanging(string value);
        partial void OnStateChanged();
        /// <summary>
        /// There are no comments for Property Zip in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Zip
        {
            get
            {
                return this._Zip;
            }
            set
            {
                this.OnZipChanging(value);
                if (object.Equals(this.Zip, value))
                {
                    return;
                }
                this._Zip = value;
                this.OnZipChanged();
                this.OnPropertyChanged("Zip");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Zip;
        partial void OnZipChanging(string value);
        partial void OnZipChanged();
        /// <summary>
        /// There are no comments for Property PrimaryPhone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PrimaryPhone
        {
            get
            {
                return this._PrimaryPhone;
            }
            set
            {
                this.OnPrimaryPhoneChanging(value);
                if (object.Equals(this.PrimaryPhone, value))
                {
                    return;
                }
                this._PrimaryPhone = value;
                this.OnPrimaryPhoneChanged();
                this.OnPropertyChanged("PrimaryPhone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PrimaryPhone;
        partial void OnPrimaryPhoneChanging(string value);
        partial void OnPrimaryPhoneChanged();
        /// <summary>
        /// There are no comments for Property SecondaryPhone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SecondaryPhone
        {
            get
            {
                return this._SecondaryPhone;
            }
            set
            {
                this.OnSecondaryPhoneChanging(value);
                if (object.Equals(this.SecondaryPhone, value))
                {
                    return;
                }
                this._SecondaryPhone = value;
                this.OnSecondaryPhoneChanged();
                this.OnPropertyChanged("SecondaryPhone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SecondaryPhone;
        partial void OnSecondaryPhoneChanging(string value);
        partial void OnSecondaryPhoneChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                if (object.Equals(this.Email, value))
                {
                    return;
                }
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property PolicyNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PolicyNumber
        {
            get
            {
                return this._PolicyNumber;
            }
            set
            {
                this.OnPolicyNumberChanging(value);
                if (object.Equals(this.PolicyNumber, value))
                {
                    return;
                }
                this._PolicyNumber = value;
                this.OnPolicyNumberChanged();
                this.OnPropertyChanged("PolicyNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PolicyNumber;
        partial void OnPolicyNumberChanging(string value);
        partial void OnPolicyNumberChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Invoices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Invoice> Invoices
        {
            get
            {
                this.@__Invoices.EnsureValueInitialized();
                return this._Invoices;
            }
            set
            {
                this._Invoices = value;
                this.OnPropertyChanged("Invoices");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Invoice> _Invoices = new global::System.Data.Services.Client.DataServiceCollection<Invoice>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Appointments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Appointment> Appointments
        {
            get
            {
                this.@__Appointments.EnsureValueInitialized();
                return this._Appointments;
            }
            set
            {
                this._Appointments = value;
                this.OnPropertyChanged("Appointments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Appointment> _Appointments = new global::System.Data.Services.Client.DataServiceCollection<Appointment>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
