//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 5/15/2016 8:42:38 PM
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// There are no comments for PrescriptionContoso in the schema.
    /// </summary>
    public partial class PrescriptionContoso : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// Initialize a new PrescriptionContoso object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PrescriptionContoso(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "LightSwitchApplication", "LightSwitchApplication.Implementation");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for ProductRebates in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ProductRebate> ProductRebates
        {
            get
            {
                if ((this._ProductRebates == null))
                {
                    this._ProductRebates = base.CreateQuery<ProductRebate>("ProductRebates");
                }
                return this._ProductRebates;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ProductRebate> _ProductRebates;
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Product> Products
        {
            get
            {
                if ((this._Products == null))
                {
                    this._Products = base.CreateQuery<Product>("Products");
                }
                return this._Products;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Product> _Products;
        /// <summary>
        /// There are no comments for ProductRebates in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProductRebates(ProductRebate productRebate)
        {
            base.AddObject("ProductRebates", productRebate);
        }
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataserv" +
                "ices/metadata\" m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\"><Schema " +
                "xmlns:annotation=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" Names" +
                "pace=\"LightSwitchApplication\" Alias=\"Self\" xmlns=\"http://schemas.microsoft.com/a" +
                "do/2008/09/edm\"><EntityType Name=\"ProductRebate\"><Key><PropertyRef Name=\"Product" +
                "RebateID\" /></Key><Property Name=\"ProductRebateID\" Type=\"Edm.Int32\" Nullable=\"fa" +
                "lse\" annotation:StoreGeneratedPattern=\"Identity\" /><Property Name=\"RebateStart\" " +
                "Type=\"Edm.DateTime\" Precision=\"0\" ConcurrencyMode=\"Fixed\" /><Property Name=\"Reba" +
                "teEnd\" Type=\"Edm.DateTime\" Precision=\"0\" ConcurrencyMode=\"Fixed\" /><Property Nam" +
                "e=\"Rebate\" Type=\"Edm.Decimal\" Precision=\"19\" Scale=\"4\" ConcurrencyMode=\"Fixed\" /" +
                "><Property Name=\"ProductID\" Type=\"Edm.Int32\" Nullable=\"false\" ConcurrencyMode=\"F" +
                "ixed\" /><NavigationProperty Name=\"Product\" Relationship=\"LightSwitchApplication." +
                "FK_Product_ProductRebate\" ToRole=\"Product\" FromRole=\"ProductRebate\" /></EntityTy" +
                "pe><EntityType Name=\"Product\"><Key><PropertyRef Name=\"ProductID\" /></Key><Proper" +
                "ty Name=\"ProductID\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedP" +
                "attern=\"Identity\" /><Property Name=\"ProductName\" Type=\"Edm.String\" Nullable=\"fal" +
                "se\" MaxLength=\"50\" ConcurrencyMode=\"Fixed\" /><Property Name=\"MSRP\" Type=\"Edm.Dec" +
                "imal\" Nullable=\"false\" Precision=\"19\" Scale=\"4\" ConcurrencyMode=\"Fixed\" /><Prope" +
                "rty Name=\"Description\" Type=\"Edm.String\" MaxLength=\"Max\" ConcurrencyMode=\"Fixed\"" +
                " /><Property Name=\"ProductImage\" Type=\"Edm.Binary\" MaxLength=\"Max\" /><Property N" +
                "ame=\"Category\" Type=\"Edm.String\" MaxLength=\"Max\" ConcurrencyMode=\"Fixed\" /><Navi" +
                "gationProperty Name=\"ProductRebates\" Relationship=\"LightSwitchApplication.FK_Pro" +
                "duct_ProductRebate\" ToRole=\"ProductRebate\" FromRole=\"Product\" /></EntityType><As" +
                "sociation Name=\"FK_Product_ProductRebate\"><End Role=\"Product\" Type=\"LightSwitchA" +
                "pplication.Product\" Multiplicity=\"1\" /><End Role=\"ProductRebate\" Type=\"LightSwit" +
                "chApplication.ProductRebate\" Multiplicity=\"*\" /><ReferentialConstraint><Principa" +
                "l Role=\"Product\"><PropertyRef Name=\"ProductID\" /></Principal><Dependent Role=\"Pr" +
                "oductRebate\"><PropertyRef Name=\"ProductID\" /></Dependent></ReferentialConstraint" +
                "></Association><EntityContainer Name=\"PrescriptionContoso\" m:IsDefaultEntityCont" +
                "ainer=\"true\"><EntitySet Name=\"ProductRebates\" EntityType=\"LightSwitchApplication" +
                ".ProductRebate\" /><EntitySet Name=\"Products\" EntityType=\"LightSwitchApplication." +
                "Product\" /><AssociationSet Name=\"FK_Product_ProductRebate\" Association=\"LightSwi" +
                "tchApplication.FK_Product_ProductRebate\"><End Role=\"Product\" EntitySet=\"Products" +
                "\" /><End Role=\"ProductRebate\" EntitySet=\"ProductRebates\" /></AssociationSet><Fun" +
                "ctionImport Name=\"RelatedProducts\" ReturnType=\"Collection(LightSwitchApplication" +
                ".Product)\" EntitySet=\"Products\" m:HttpMethod=\"GET\"><Parameter Name=\"Category\" Ty" +
                "pe=\"Edm.String\" Mode=\"In\" /></FunctionImport><FunctionImport Name=\"Microsoft_Lig" +
                "htSwitch_GetCanInformation\" ReturnType=\"Edm.String\" m:HttpMethod=\"GET\"><Paramete" +
                "r Name=\"dataServiceMembers\" Type=\"Edm.String\" Mode=\"In\" /></FunctionImport></Ent" +
                "ityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.ProductRebate in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductRebateID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ProductRebates")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProductRebateID")]
    public partial class ProductRebate : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ProductRebate object.
        /// </summary>
        /// <param name="productRebateID">Initial value of ProductRebateID.</param>
        /// <param name="productID">Initial value of ProductID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ProductRebate CreateProductRebate(int productRebateID, int productID)
        {
            ProductRebate productRebate = new ProductRebate();
            productRebate.ProductRebateID = productRebateID;
            productRebate.ProductID = productID;
            return productRebate;
        }
        /// <summary>
        /// There are no comments for Property ProductRebateID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProductRebateID
        {
            get
            {
                return this._ProductRebateID;
            }
            set
            {
                this.OnProductRebateIDChanging(value);
                if (object.Equals(this.ProductRebateID, value))
                {
                    return;
                }
                this._ProductRebateID = value;
                this.OnProductRebateIDChanged();
                this.OnPropertyChanged("ProductRebateID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProductRebateID;
        partial void OnProductRebateIDChanging(int value);
        partial void OnProductRebateIDChanged();
        /// <summary>
        /// There are no comments for Property RebateStart in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> RebateStart
        {
            get
            {
                return this._RebateStart;
            }
            set
            {
                this.OnRebateStartChanging(value);
                if (object.Equals(this.RebateStart, value))
                {
                    return;
                }
                this._RebateStart = value;
                this.OnRebateStartChanged();
                this.OnPropertyChanged("RebateStart");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _RebateStart;
        partial void OnRebateStartChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnRebateStartChanged();
        /// <summary>
        /// There are no comments for Property RebateEnd in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> RebateEnd
        {
            get
            {
                return this._RebateEnd;
            }
            set
            {
                this.OnRebateEndChanging(value);
                if (object.Equals(this.RebateEnd, value))
                {
                    return;
                }
                this._RebateEnd = value;
                this.OnRebateEndChanged();
                this.OnPropertyChanged("RebateEnd");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _RebateEnd;
        partial void OnRebateEndChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnRebateEndChanged();
        /// <summary>
        /// There are no comments for Property Rebate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Rebate
        {
            get
            {
                return this._Rebate;
            }
            set
            {
                this.OnRebateChanging(value);
                if (object.Equals(this.Rebate, value))
                {
                    return;
                }
                this._Rebate = value;
                this.OnRebateChanged();
                this.OnPropertyChanged("Rebate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Rebate;
        partial void OnRebateChanging(global::System.Nullable<decimal> value);
        partial void OnRebateChanged();
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                if (object.Equals(this.ProductID, value))
                {
                    return;
                }
                this._ProductID = value;
                this.OnProductIDChanged();
                this.OnPropertyChanged("ProductID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Product Product
        {
            get
            {
                this.@__Product.EnsureValueInitialized();
                return this._Product;
            }
            set
            {
                Product previous = this.Product;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Product = null;
                    this.@__Product.OnValueSet();
                    previous.ProductRebates.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.ProductID = value.ProductID;
                    }
                    else
                    {
                        this.ProductID = default(int);
                    }
                }
                this._Product = value;
                this.@__Product.OnValueSet();
                if ((value != null))
                {
                    value.@__ProductRebates.Add(this);
                }
                this.___OnPropertyChanged("Product");
                this.OnPropertyChanged("Product");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Product _Product;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Products")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProductID")]
    public partial class Product : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="productName">Initial value of ProductName.</param>
        /// <param name="mSRP">Initial value of MSRP.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Product CreateProduct(int productID, string productName, decimal mSRP)
        {
            Product product = new Product();
            product.ProductID = productID;
            product.ProductName = productName;
            product.MSRP = mSRP;
            return product;
        }
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                if (object.Equals(this.ProductID, value))
                {
                    return;
                }
                this._ProductID = value;
                this.OnProductIDChanged();
                this.OnPropertyChanged("ProductID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property ProductName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductName
        {
            get
            {
                return this._ProductName;
            }
            set
            {
                this.OnProductNameChanging(value);
                if (object.Equals(this.ProductName, value))
                {
                    return;
                }
                this._ProductName = value;
                this.OnProductNameChanged();
                this.OnPropertyChanged("ProductName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductName;
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        /// <summary>
        /// There are no comments for Property MSRP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal MSRP
        {
            get
            {
                return this._MSRP;
            }
            set
            {
                this.OnMSRPChanging(value);
                if (object.Equals(this.MSRP, value))
                {
                    return;
                }
                this._MSRP = value;
                this.OnMSRPChanged();
                this.OnPropertyChanged("MSRP");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _MSRP;
        partial void OnMSRPChanging(decimal value);
        partial void OnMSRPChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                if (object.Equals(this.Description, value))
                {
                    return;
                }
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ProductImage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] ProductImage
        {
            get
            {
                if ((this._ProductImage != null))
                {
                    return ((byte[])(this._ProductImage.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnProductImageChanging(value);
                if (object.Equals(this.ProductImage, value))
                {
                    return;
                }
                this._ProductImage = value;
                this.OnProductImageChanged();
                this.OnPropertyChanged("ProductImage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _ProductImage;
        partial void OnProductImageChanging(byte[] value);
        partial void OnProductImageChanged();
        /// <summary>
        /// There are no comments for Property Category in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                if (object.Equals(this.Category, value))
                {
                    return;
                }
                this._Category = value;
                this.OnCategoryChanged();
                this.OnPropertyChanged("Category");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Category;
        partial void OnCategoryChanging(string value);
        partial void OnCategoryChanged();
        /// <summary>
        /// There are no comments for ProductRebates in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ProductRebate> ProductRebates
        {
            get
            {
                this.@__ProductRebates.EnsureValueInitialized();
                return this._ProductRebates;
            }
            set
            {
                this._ProductRebates = value;
                this.OnPropertyChanged("ProductRebates");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ProductRebate> _ProductRebates = new global::System.Data.Services.Client.DataServiceCollection<ProductRebate>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
